### ISSUE TITLE
error on gatsby develop

### ISSUE THREAD

**Issue by daysgobye** [MassivDash/gatsby-source-woocommerce#1]
![image](https://user-images.githubusercontent.com/38364556/54801759-00f87400-4c2e-11e9-9ab7-4015dcc2ad33.png)
I am getting this error when I do gatsby develop 
this id from my config 
    {
      resolve: "@massivdash/gatsby-source-woocommerce",
      options: {
        // Base URL of Wordpress site
        api: 'playg my domain old.net',

        // This counts controls the API get with ?per_page=
        // default: 10
        itemCount: 20,

        // set to true to see fetch output in console, during build 
        // default: false
        verbose: true,

        // true if using https. false if nah.
        https: true,
        
        // Array of strings with fields you'd like to create nodes for...
        api_keys: {
          consumer_key: "ck_fe9b7c27522a71my real key a8a7eb956a8",
          consumer_secret: "cs_9f3472c314my real key b6a125723d189a06c3"
        },
        fields: ['products']
      }
    }

**Comment by staffordrose** [comment]
@daysgobye Any luck with this? I'm getting the same error

**Comment by zamson** [comment]
Hey guys, did you find a solution? I could fetch all data on the first go but now when running `gatsby develop` I get this error.

**Comment by MassivDash** [comment]
Hello, Please provide (if you can) the full configuration file (gatsby config), and node version so I could investigate more on this issue?
